### ISSUE TITLE
Path to init not correct

### ISSUE THREAD

**Issue by qds-soft** [carlonluca/docker-vnc-desktop#1]
Hi Luca,
first of all, a big thank you for the project. It's really useful for me.

## Issue
I built a docker image with the Dockerfile you provided. But as soon as I ran the container, an error occurred:
The `startup.sh` couldn't execute it's last line (39) of code

```
exec /usr/bin/tini -- supervisord -n -c /etc/supervisor/supervisord.conf
```

because in the Dockerfile we copied tini  to `/bin/tini`:

```
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /bin/tini
``` 

## Solution

Changing the last line (39) to

```
exec /bin/tini -- supervisord -n -c /etc/supervisor/supervisord.conf
```

and rebuilding the image did the trick for me.

You can add those changes to the project if you'd like.

**Comment by carlonluca** [comment]
Thank you for letting me know. I changed the path in the Dockerfile as the script is shared with the Ubuntu variant.
