### ISSUE TITLE
Can't use without user password.

### ISSUE THREAD

**Issue by Nostradamus1973** [carlonluca/docker-vnc-desktop#2]
Good afternoon,
I've managed to install your xfce docker and I would like to thank you because yours in the only one that worked for me.
However, I managed to change the username, but, I can't figure out the password.

Can you please help?

Thank you and have a nice day.

EDIT: I found it in  your text file, thx again for all your hard work

**Comment by carlonluca** [comment]
Thanks for pointing this out. I added a note with the default credentials.
